// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJNqVeL6D1qnsF2RUiGDiBUrZISNlv5uY',
    appId: '1:404081097054:web:893b6216b4d553aad1b7cf',
    messagingSenderId: '404081097054',
    projectId: 'fir-test-37b46',
    authDomain: 'fir-test-37b46.firebaseapp.com',
    storageBucket: 'fir-test-37b46.firebasestorage.app',
    measurementId: 'G-C818DEH6Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zMSZWkxKSE5Vb8K09UHkgyS5eEtqAY4',
    appId: '1:404081097054:android:cc2d6aa5638de578d1b7cf',
    messagingSenderId: '404081097054',
    projectId: 'fir-test-37b46',
    storageBucket: 'fir-test-37b46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSGNgnPk89FHCn9nGBHDo3sWuKrcXS0A',
    appId: '1:404081097054:ios:cb5bbbb3c98b365fd1b7cf',
    messagingSenderId: '404081097054',
    projectId: 'fir-test-37b46',
    storageBucket: 'fir-test-37b46.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
